# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comunicacion.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63omunicacion.proto\"N\n\x12instructionRequest\x12\x10\n\x08peticion\x18\x01 \x01(\t\x12\x15\n\rnombreArchivo\x18\x02 \x01(\t\x12\x0f\n\x07\x61rchivo\x18\x03 \x01(\x0c\"L\n\x0fmessageResponse\x12\x11\n\trespuesta\x18\x01 \x01(\t\x12\x15\n\rnombreArchivo\x18\x02 \x01(\t\x12\x0f\n\x07\x61rchivo\x18\x03 \x01(\x0c\x32\x44\n\x0emessageService\x12\x32\n\x07message\x12\x13.instructionRequest\x1a\x10.messageResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comunicacion_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSTRUCTIONREQUEST._serialized_start=22
  _INSTRUCTIONREQUEST._serialized_end=100
  _MESSAGERESPONSE._serialized_start=102
  _MESSAGERESPONSE._serialized_end=178
  _MESSAGESERVICE._serialized_start=180
  _MESSAGESERVICE._serialized_end=248
# @@protoc_insertion_point(module_scope)
